/* =========================
   Fallbacks
========================= */
export const WHITE_PIXEL =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMB/aeuFJ0AAAAASUVORK5CYII=";

export const NORMAL_NEUTRAL = WHITE_PIXEL;

/* =========================
   Materiales
========================= */
export const MATERIALES = {
  pino: {
    label: "Pino natural",
    color: "#ffffff",
    roughness: 0.75,
    metalness: 0.0,
    mapUrl: "/materiales/pino.jpg",
    normalUrl: "",
    roughUrl: "",
    repeat: [1.25, 1.25],
    clearcoat: 0.05,
    clearcoatRoughness: 0.65,
    specularIntensity: 0.25,
    envMapIntensity: 0.65,
  },
  roble: {
    label: "Roble claro",
    color: "#d8b27c",
    roughness: 0.58,
    metalness: 0,
    mapUrl: "/materiales/pino.jpg",
    normalUrl: "",
    roughUrl: "",
    repeat: [1.6, 1.1],
    clearcoat: 0.18,
    clearcoatRoughness: 0.5,
    specularIntensity: 0.35,
    envMapIntensity: 0.75,
  },
  nogal: {
    label: "Nogal oscuro",
    color: "#6b4528",
    roughness: 0.62,
    metalness: 0,
    mapUrl: "/materiales/pino.jpg",
    normalUrl: "",
    roughUrl: "",
    repeat: [1.35, 1.0],
    clearcoat: 0.16,
    clearcoatRoughness: 0.58,
    specularIntensity: 0.3,
    envMapIntensity: 0.62,
  },
  melamina_blanca: {
    label: "Melamina blanca",
    color: "#ffffff",
    roughness: 0.28,
    metalness: 0.02,
    mapUrl: "/materiales/melamina_blanca.jpg",
    normalUrl: "",
    roughUrl: "",
    repeat: [1.0, 1.0],
    clearcoat: 0.85,
    clearcoatRoughness: 0.06,
    specularIntensity: 0.9,
    envMapIntensity: 1.25,
  },
  melamina_negra: {
    label: "Melamina negra",
    color: "#ffffff",
    roughness: 3.25,
    metalness: 0.02,
    mapUrl: "/materiales/melamina_negra.jpg",
    normalUrl: "",
    roughUrl: "",
    repeat: [1.0, 1.0],
    clearcoat: 0.9,
    clearcoatRoughness: 0.07,
    specularIntensity: 1.0,
    envMapIntensity: 0.15,
  },
  grafito: {
    label: "Grafito satinado",
    color: "#32343a",
    roughness: 0.42,
    metalness: 0.02,
    mapUrl: WHITE_PIXEL,
    normalUrl: "",
    roughUrl: "",
    repeat: [1, 1],
    clearcoat: 0.45,
    clearcoatRoughness: 0.2,
    specularIntensity: 0.65,
    envMapIntensity: 0.55,
  },
  verde_oliva: {
    label: "Verde oliva",
    color: "#66705b",
    roughness: 0.48,
    metalness: 0.01,
    mapUrl: WHITE_PIXEL,
    normalUrl: "",
    roughUrl: "",
    repeat: [1, 1],
    clearcoat: 0.35,
    clearcoatRoughness: 0.24,
    specularIntensity: 0.5,
    envMapIntensity: 0.7,
  },
  metal_cromado: {
    label: "Metal cromado",
    color: "#d6d8dc",
    roughness: 0.16,
    metalness: 0.82,
    mapUrl: WHITE_PIXEL,
    normalUrl: "",
    roughUrl: "",
    repeat: [1, 1],
    clearcoat: 0.2,
    clearcoatRoughness: 0.08,
    specularIntensity: 1,
    envMapIntensity: 1.4,
  },
};
